name: Angular CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # chemin du dossier de cache et clé de cache
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npx ng lint

      - name: Run Prettier Check
        run: npx prettier --check .

      - name: Run Tests
        run: npx ng test --watch=false --browsers=ChromeHeadlessCI --code-coverage

      - name: Build Project
        run: npx ng build --prod --aot
